image: openjdk:8-jdk

install:
  - apt update && apt install -y git curl
  - curl -o notify.sh https://cocytus.services/ci/github-notif.sh && chmod +x notify.sh
  - chmod +x gradlew

script:
  - ./gradlew clean
  - ./gradlew build
