mod_id=gamemodebuild
mod_version=1.2.0
minecraft_version=26.1.2

neo_version=26.1.2.64-beta

# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

