modLoader="javafml"
loaderVersion="[36,)"
issueTrackerURL="https://github.com/LoveTropics/GamemodeBuild"
license="ARR"

[[mods]]
modId="gamemodebuild"
version="${file.jarVersion}"
displayName="Gamemode Build"
credits=""
authors="tterrag, Gegy"
description='''
Creative mode without creative. Great for collaborative public building.
'''
[[dependencies.gamemodebuild]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gamemodebuild]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,)"
    ordering="NONE"
    side="BOTH"
